platform: linux
image_resource:
    type: docker-image
    source:
       repository: platformengineering/concourse-ansible-resource
       tag: "latest"
inputs:
- name: wiki-server

outputs:
- name: wiki-server-palybooks
run:
   path: /bin/bash
   args:
      - -c
      - | 
          pwd
          ls
          ls wiki-server/
          ansible-playbook -u mxd87jv -s -i inventroy  wiki.yml
          
