platform: linux
image_resource:
    type: docker-image
    source:
       repository: 172.25.160.229:5000/ansible
       tags: "latest"
       insecure_registries: ["172.25.160.229:5000"]
inputs:
- name: wiki-server

outputs:
- name: wiki-server-test
run:
   path: /bin/bash
   args:
      - -c
      - |
        ansible-playbook -v -i /tmp/inventory /tmp/playbook.yml -u mxd87jv --private-key /tmp/tsa_host_key
