resources:
- name: wiki-server
  type: git
  source:
    uri: https://github.com/mohammad-dabour/dummyProject.git
    password: {{PASS}}
    username: {{USER}}
    branch: master

- name: nginx-server
  type: git
  source:
    uri: https://github.com/mohammad-dabour/docker-nginx.git
    password: {{PASS}}
    username: {{USER}}
    branch: master

- name: wikigoapp-docker
  type: docker-image
  source:
    repository: mdab0ur/wikigoapp
    username: {{USER}}
    password: {{PASS}}

- name: nginx-docker
  type: docker-image
  source:
    repository: mdab0ur/concourse
    username: {{USER}}
    password: {{PASS}}

jobs:
- name: wikiserver-test
  plan:
    - get: wiki-server
      trigger: true
    - task: test-wikiserver
      file: wiki-server/ci/tasks/test-task.yml
    - task: publish-testing-results-wikiserver
      file: wiki-server/ci/tasks/test-publish.yml
- name: build-wiki
  plan:
    - get: wiki-server
      trigger: true
      passed: [wikiserver-test]
    - task: task-build
      file: wiki-server/ci/tasks/task-build.yml
    - put: wikigoapp-docker
      params: {build: "wiki-build"}

- name: docker-nginx-build
  plan:
    - get: nginx-server
    - put: nginx-docker
      params: {build: nginx-server}

- name: job-deploy-app
  plan:
    - get: nginx-server
      trigger: true
      passed: [docker-nginx-build]
    - get: wiki-server
      trigger: true
      passed: [build-wiki]
    - task: run-docker-ansible
      config:
        platform: linux
        image_resource:
            type: docker-image
            source:
              repository: ((reg_address)):5000/ansible
              insecure_registries: ["((reg_address)):5000"]
        params:
           USER: {{docker_user}}
           password: {{PASS}}
           username: {{USER}}
        run:
         path: /bin/bash
         args:
           - -c
           - |
              ansible-playbook -v -i /tmp/inventory /tmp/playbook.yml -u $USER --private-key /tmp/tsa_host_key --sudo --extra-vars "remoteUser=$USER user=$username pass=$password"





